### Each yaml file defines an experiment configuration
### NOTE: For label consistency, use the same format as in common/labels.py
exp_name: "date-number-title"
interactive: False # whether to run in input-output mode (for trial and debugging, no data collection), or batch mode (for experiments)
exp_type: Experiment.LINEAR # used to determine experiment logic / topology
optional_configs:
  experiment_repetitions: 5 # number of times to repeat experiment for each exp graph setup

  # For TAP
  branching_factor: 4 # at each iteration, number of new prompts to generate from each seed prompt
  width: 10 # number of total candidates to keep at the end of each iteration
  depth: 10 # maximum number of iterations to run, before giving up
  keep_last_n_rounds: 3 # number of rounds of conversation history that the attacker LLM can access
  # also check other specific experiment setup configs

  # For utility experiments
  generate_only: True
  evaluate_only: False
  # check utility experiment setup configs

### Attack sets: each set configures an attack graph
attack_sets:
  - name: "prefix"
    attack_sequence:
      # either just a string label (means no optional configs)
      - Attack.PREFIX
      # or a dict with label and optional configs
      - label: Attack.REFUSAL_SUPPRESSION
        optional_configs:
          # these will be used as params for the constructor method of the node class
          key: value
    optional_configs:
      key: value

### Defense sets: each set configures a defense graph
defense_sets:
  - name: "vicuna13b-only"
    # All the following will be applied in this order
    defense_sequence_before_llm:
      - Defense.PROMPT_GUARD
    target_llm: LLM.VICUNA_13B
    defense_sequence_after_llm:
      - Defense.LLAMA_GUARD
    optional_configs:
      key: value

### Evaluation set: the evaluation process to obtain metrics, will be applied after each attack-defense combination
### Compulsory for batch mode, optional for interactive mode
evaluation_set:
  name: "oss-jb-judge_jbb"
  evaluator_sequence:
    - Evaluator.OSS_JB_JUDGE_120B
  dataset: Dataset.JBB_BEHAVIOURS
  optional_configs:
    key: value
