import gc
import torch
import os
import json
import logging
import time
from alpaca_eval.main import evaluate

from exp.build_graph import build_defense_graph
from common.constants import REJECTION_MESSAGE

# Default values of optional configs
EXPERIMENT_REPETITIONS = 1
OPTIMISE_MEMORY = False
GENERATE_ONLY = False # load from original reference outputs file, run full defense graph to generate outputs for model under test, save outputs file
EVALUATE_ONLY = False # load outputs file generated by model under test, evaluate against reference outputs file, save results
TEST_INPUT_FILTER_ONLY = False # a special case: for a given reference outputs file, run it only through input filters in defense set, if rejected, update output to be rejection message; if not, keep original output
TEST_OUTPUT_FILTER_ONLY = False # a special case: for a given reference outputs file, run it only through output filters in defense set, if rejected, update output to be rejection message; if not, keep original output
TEST_LATENCY = False # only valid with generate_only; measures total generation time and writes timing results to save_dir
REFERENCE_OUTPUTS_FILENAME = "reference_model.json"

alpaca_eval_model_outputs_path = "data/alpaca_eval_model_outputs"


class UtilityExperiment():
    def __init__(self, exp_name:str, defense_sets: list, save_dir: str, optional_configs: dict):
        self.exp_name = exp_name
        self.defense_sets = defense_sets
        self.save_dir = save_dir
        self.experiment_repetitions = EXPERIMENT_REPETITIONS # currently fix to 1, implement later if needed
        self.optimise_memory = optional_configs.get("optimise_memory", OPTIMISE_MEMORY)
        self.generate_only = optional_configs.get("generate_only", GENERATE_ONLY)
        self.evaluate_only = optional_configs.get("evaluate_only", EVALUATE_ONLY)
        self.test_input_filter_only = optional_configs.get("test_input_filter_only", TEST_INPUT_FILTER_ONLY)
        self.test_output_filter_only = optional_configs.get("test_output_filter_only", TEST_OUTPUT_FILTER_ONLY)
        self.test_latency = optional_configs.get("test_latency", TEST_LATENCY)
        self.reference_outputs_filename = optional_configs.get("reference_outputs_filename", REFERENCE_OUTPUTS_FILENAME)
        self.reference_outputs_path = os.path.join(alpaca_eval_model_outputs_path, self.reference_outputs_filename)
        if not os.path.exists(self.reference_outputs_path):
            raise ValueError(f"Reference outputs file {self.reference_outputs_path} does not exist. Please check your config.")
        self.eval_set = json.load(open(self.reference_outputs_path, "r"))
        self.subfolder_name = optional_configs.get("subfolder_name", None)

        # backward compatibility for previous naming of "generate_and_evaluate"
        generate_and_evaluate = optional_configs.get("generate_and_evaluate", None)
        if generate_and_evaluate == True:
            self.evaluate_only = True
        elif generate_and_evaluate == False:
            self.generate_only = True
        
        assert sum([self.generate_only, self.evaluate_only, self.test_input_filter_only, self.test_output_filter_only]) == 1, "In utility exp config, one and only one of generate_only, evaluate_only, test_input_filter_only, test_output_filter_only must be True"
        assert not self.test_latency or self.generate_only, "In utility exp config, test_latency=True is only valid when generate_only=True"

        if self.test_input_filter_only or self.test_output_filter_only:
            assert "reference_outputs_filename" in optional_configs, "For test_input_filter_only or test_output_filter_only, reference_outputs_filename must be specified in optional_configs"

    def run(self):
        print("\n=== Running utility evaluation with AlpacaEval ===", flush=True)
        print("\n--- Defense sets ---", flush=True)
        for d_set in self.defense_sets:
            print(f"  - {d_set['name']}", flush=True)
        
        if not self.evaluate_only:
            # for the other 3 tasks (generate / test input filter / test output filter), generate model outputs accordingly
            for d_set in self.defense_sets:
                print(f"\n--- Generating outputs for defense set {d_set['name']}' ---", flush=True)
                model_output_save_path = os.path.join(alpaca_eval_model_outputs_path, f"{d_set['name']}.json")
                model_output_exists = os.path.exists(model_output_save_path)
                save_model_outputs = not model_output_exists
                if model_output_exists and not self.test_latency:
                    print(f"  - {model_output_save_path} already exists, skipping generation", flush=True)
                    continue
                elif model_output_exists and self.test_latency:
                    print(f"  - {model_output_save_path} already exists; rerunning generation for latency test without saving outputs", flush=True)
                
                if self.generate_only:
                    # For generate_only, we run the full defense graph and save the final outputs for evaluation
                    defense_graph = build_defense_graph(d_set)
                    eval_set_copy = self.eval_set.copy()
                    latency_start_time = time.perf_counter() if self.test_latency else None
                    for i, example in enumerate(eval_set_copy):
                        if i % 10 == 0:
                            print(f" - Finished generating {i} / {len(eval_set_copy)} examples", flush=True)
                        init_state = {
                            "goal": example["instruction"],
                            "prompt": example["instruction"],
                            "messages": [],
                            "messageHistoryForTargetModel": [],
                            "rejected": False,
                            "rejector": "",
                            "reject_reason": "",
                            "jailbroken": False,
                            "evaluator_output": "",
                        }
                        final_state = defense_graph.invoke(init_state)
                        example["output"] = final_state["messages"][-1].content if len(final_state.get("messages", [])) > 0 else ""
                        example["generator"] = d_set['name']
                    if self.test_latency:
                        total_generation_time = time.perf_counter() - latency_start_time
                        latency_output_path = os.path.join(self.save_dir, f"{d_set['name']}_latency.txt")
                        with open(latency_output_path, "w") as f:
                            f.write("--- Latency test results ---\n")
                            f.write(f"Defense set: {d_set['name']}\n")
                            f.write(f"Number of examples: {len(eval_set_copy)}\n")
                            f.write(f"Total generation time: {total_generation_time:.6f} seconds\n")
                            f.write(f"Average generation time per example: {total_generation_time / len(eval_set_copy):.6f} seconds\n")
                
                elif self.test_input_filter_only:
                    # For test_input_filter_only, first validate there is only defense before the LLM, then load the instructions from reference outputs file, run the input filter on them, and save the filtered instructions for evaluation
                    if len(d_set["defense_sequence_after_llm"]) > 0:
                        logging.error(f"Warning: defense set {d_set['name']} has defenses after LLM, but we are in test_input_filter_only mode. Only defenses before LLM will be applied and evaluated.")
                        d_set["defense_sequence_after_llm"] = []
                    if d_set['target_llm'] != "LLM.PLACEHOLDER":
                        logging.error(f"Warning: defense set {d_set['name']} has target LLM {d_set['target_llm']}, but we are in test_input_filter_only mode. The target LLM will be ignored, and only defenses before LLM will be applied and evaluated.")
                        d_set['target_llm'] = "LLM.PLACEHOLDER"
                    defense_graph = build_defense_graph(d_set)
                    eval_set_copy = self.eval_set.copy()
                    for i, example in enumerate(eval_set_copy):
                        if i % 10 == 0:
                            print(f" - Finished testing input filter for {i} / {len(eval_set_copy)} examples", flush=True)
                        init_state = {
                            "goal": example["instruction"],
                            "prompt": example["instruction"],
                            "messages": [],
                            "messageHistoryForTargetModel": [],
                            "rejected": False,
                            "rejector": "",
                            "reject_reason": "",
                            "jailbroken": False,
                            "evaluator_output": "",
                        }
                        final_state = defense_graph.invoke(init_state)
                        example["generator"] = d_set['name']
                        if final_state["rejected"]:
                            example["output"] = REJECTION_MESSAGE
                
                elif self.test_output_filter_only:
                    # For test_output_filter_only, first validate there is only defense after the LLM, then load the outputs from reference outputs file, run the output filter on them, and save the filtered outputs for evaluation
                    if len(d_set["defense_sequence_before_llm"]) > 0:
                        logging.error(f"Warning: defense set {d_set['name']} has defenses before LLM, but we are in test_output_filter_only mode. Only defenses after LLM will be applied and evaluated.")
                        d_set["defense_sequence_before_llm"] = []
                    if d_set['target_llm'] != "LLM.PLACEHOLDER":
                        logging.error(f"Warning: defense set {d_set['name']} has target LLM {d_set['target_llm']}, but we are in test_output_filter_only mode. The target LLM will be ignored, and only defenses after LLM will be applied and evaluated.")
                        d_set['target_llm'] = "LLM.PLACEHOLDER"
                    defense_graph = build_defense_graph(d_set)
                    eval_set_copy = self.eval_set.copy()
                    for i, example in enumerate(eval_set_copy):
                        if i % 10 == 0:
                            print(f" - Finished testing output filter for {i} / {len(eval_set_copy)} examples", flush=True)
                        init_state = {
                            "goal": example["instruction"],
                            "prompt": example["instruction"],
                            "messages": [
                                {"role": "user", "content": example["instruction"]},
                                {"role": "assistant", "content": example["output"]},
                            ],
                            "messageHistoryForTargetModel": [],
                            "rejected": False,
                            "rejector": "",
                            "reject_reason": "",
                            "jailbroken": False,
                            "evaluator_output": "",
                        }
                        final_state = defense_graph.invoke(init_state)
                        example["generator"] = d_set['name']
                        if final_state["rejected"]:
                            example["output"] = REJECTION_MESSAGE

                if save_model_outputs:
                    with open(model_output_save_path, "w") as f:
                        json.dump(eval_set_copy, f, indent=2)
                del defense_graph
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()
                    torch.cuda.ipc_collect()
                gc.collect()

        if self.evaluate_only:
            # For evaluate_only, we load the generated outputs file for each defense set, evaluate them against the reference outputs file with AlpacaEval, and save the evaluation results
            print("\n--- Evaluating generated outputs ---", flush=True)
            for d_set in self.defense_sets:
                name = d_set['name']
                result_output_path = os.path.join(self.save_dir, f"{name}.txt")
                model_output_save_path = os.path.join(alpaca_eval_model_outputs_path, '' if self.subfolder_name is None else self.subfolder_name, f"{name}.json")
                print(f"\n--- Evaluating defense set {name}' ---", flush=True)
                if not os.path.exists(model_output_save_path):
                    print(f"  - {model_output_save_path} does not exist, skipping evaluation", flush=True)
                    continue
                leaderboard, _ = evaluate(
                    model_outputs=model_output_save_path,
                    reference_outputs=self.reference_outputs_path,
                    annotators_config="weighted_alpaca_eval_vllm_llama3_70b",
                    is_return_instead_of_print=True,
                )
                with open(result_output_path, "w") as f:
                    f.write("--- Defense config ---\n")
                    for d in d_set["defense_sequence_before_llm"]:
                        f.write(f"{d}\n")
                    f.write(f"{d_set['target_llm']}\n")
                    for d in d_set["defense_sequence_after_llm"]:
                        f.write(f"{d}\n")
                    
                    result = leaderboard[["length_controlled_winrate", "lc_standard_error", "win_rate", "standard_error"]]
                    f.write("\n--- Evaluation results ---\n")
                    f.write(result.to_string())

        print("\n=== Batch experiment complete ===", flush=True)
